### PR TITLE
Try another password when new PdfReader() failed with wrong password.

### PR DESCRIPTION
**Pull request by kurema**
Currently, the best way to try multiple password I think is `new PdfReader()` each time. This takes time to load the file. Using `RandomAccessFileOrArray()` is faster but it throws `NullReferenceException` in my environment (UWP).
I have some idea to fix it.
1. Add `IEnumerable<byte[]> Passwords` to PdfReader.
2. Add `Func<Task<byte[]>> PasswordRequestCallback` to PdfReader. In this case user can input with something like `await dialog.ShowMessage()` when password is wrong.
3. Update BadPasswordException to support `TryPassword()`.

This is my implementation of 3.

Usage:
```cs
try
{
	using var reader = new PdfReader(inputFile);
}
catch (BadPasswordException pe)
{
	if (pe.CanTryPassword)
	{
		string correctPassword = null;
		foreach (var candidate in new string[] { "password", "owner" })
		{
			switch (pe.TryPassword(Encoding.UTF8.GetBytes(candidate)))
			{
				case BadPasswordException.PasswordTestResult.SuccessOwnerPassword:
				case BadPasswordException.PasswordTestResult.SuccessUserPassword:
					correctPassword = candidate;
					break;
			}
			if (correctPassword is not null) break;
		}
		//Do something.
	}
}
```

There's some issue with my PR.

1. There's long duplicate code especially when `RValue >= 6`. It makes maintenance cumbersome.
2. `BadPasswordException.TryPassword()` is bit weird.
3. You may not like BadPasswordException.PasswordTestResult.
4. You still have to `new PdfReader()` twice.

The problem can be improved to some extent by cutting out the second half of readDecryptedDocObj() into a separate function, but it requires many arguments.

### CODE REVIEW

**Comment by VahidN** [comment]
Use [AllowOpenWithFullPermissions](https://github.com/VahidN/iTextSharp.LGPLv2.Core/blob/77ec36d2361d9367bcd5803fd4512520b5d84573/src/iTextSharp.LGPLv2.Core.FunctionalTests/Issues/Issue100.cs#L308) instead.

**Comment by kurema** [comment]
You don't need the owner password with [AllowOpenWithFullPermissions](https://github.com/VahidN/iTextSharp.LGPLv2.Core/blob/77ec36d2361d9367bcd5803fd4512520b5d84573/src/iTextSharp.LGPLv2.Core.FunctionalTests/Issues/Issue100.cs#L308), but you still need the user password to open. When you don't know the user password, you still need to new multiple time. And in that case `Tokens = new PrTokeniser(new RandomAccessFileOrArray(url));` is called each time that's slow.
If you mean you just want `TryPassword()` to return `bool?` instead of `PasswordTestResult`, following fix may help. And make some other `internal`.

```cs
public bool? TryPassword(byte[] password)
{
	if (Tester is null) return null;
	return Tester.Invoke(password) switch { PasswordTestResult.SuccessOwnerPassword => true, PasswordTestResult.SuccessUserPassword => true, _ => false };
}
```

**Comment by kurema** [comment]
And yes, when you know the user password and not the owner password, you should use AllowOpenWithFullPermissions. You can't get `BadPasswordException` so this method doesn't work.

**Comment by VahidN** [comment]
And in that case new PrTokeniser(new RandomAccessFileOrArray()); and ReadPdf(); is called each time that's slow.

I don't care. I'm not going to change anything here. Stop it.

**Pull request closed without merging**
